# Generated by Django 3.1.1 on 2020-12-03 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='hsk_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
            preserve_default=False,
        ),
    ]
