# Generated by Django 3.1.4 on 2021-02-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='weight_class',
            field=models.CharField(choices=[('Fly', 'Flyweight'), ('Bantam', 'Bantamweight'), ('Feather', 'Featherweight'), ('Light', 'Lightweight'), ('Welter', 'Welterweight'), ('Middle', 'Middleweight'), ('Light Heavy', 'Light Heavyweight'), ('Heavy', 'Heavyweight')], max_length=35),
        ),
    ]
