# Generated by Django 3.1.4 on 2021-02-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0002_auto_20210205_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='p4p_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
