# Generated by Django 3.1.1 on 2020-12-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0003_auto_20201203_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='pingyin',
            new_name='pinyin',
        ),
    ]
