# Generated by Django 3.1.4 on 2021-03-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0004_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_description',
            field=models.CharField(default='non', max_length=250),
            preserve_default=False,
        ),
    ]
