# Generated by Django 3.1.4 on 2020-12-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0004_auto_20201203_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=5)),
                ('image', models.CharField(max_length=45)),
                ('suit', models.CharField(max_length=7)),
            ],
        ),
    ]
