# Generated by Django 3.1.4 on 2020-12-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0005_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='suit',
            field=models.CharField(max_length=8),
        ),
    ]
