# Generated by Django 3.1.4 on 2020-12-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0006_auto_20201222_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='card',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
