# Generated by Django 3.1.4 on 2021-03-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0006_storeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_link',
            field=models.CharField(default='link', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeitem',
            name='product_link',
            field=models.CharField(default='link', max_length=250),
            preserve_default=False,
        ),
    ]
