# Generated by Django 3.1.4 on 2021-01-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0007_auto_20201222_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('example', models.CharField(blank=True, max_length=50, null=True)),
                ('example_type', models.CharField(blank=True, max_length=50, null=True)),
                ('definition', models.TextField(max_length=2000)),
            ],
        ),
    ]
