# Generated by Django 3.1.4 on 2021-03-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0008_auto_20210315_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail_url',
            field=models.CharField(max_length=250),
        ),
    ]
