# Generated by Django 3.1.4 on 2021-01-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0008_dictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3000)),
                ('tutorial', models.CharField(max_length=100)),
                ('mistakes', models.CharField(max_length=100)),
            ],
        ),
    ]
