# Generated by Django 3.1.4 on 2021-01-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0009_technique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='name',
            new_name='title',
        ),
    ]
