# Generated by Django 3.1.4 on 2021-04-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0010_auto_20210315_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='status',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
