# Generated by Django 3.1.4 on 2021-01-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0011_fighter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='height',
            field=models.CharField(max_length=10),
        ),
    ]
