# Generated by Django 3.1.4 on 2021-04-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0011_fighter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='legend',
            field=models.BooleanField(default=False),
        ),
    ]
