# Generated by Django 3.1.4 on 2021-04-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0012_fighter_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='highlights',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
