# Generated by Django 3.1.4 on 2021-01-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0012_auto_20210112_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='reach',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
