# Generated by Django 3.1.4 on 2021-01-12 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0013_auto_20210112_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='weight_class',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(105), django.core.validators.MaxValueValidator(265)]),
        ),
    ]
