# Generated by Django 3.1.4 on 2021-06-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0014_fighter_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
