# Generated by Django 3.1.4 on 2021-06-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0015_auto_20210616_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
