# Generated by Django 3.1.4 on 2021-01-13 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0015_auto_20210112_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='notable_wins',
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(blank=True, choices=[('Red Corner', 'red'), ('Blue Corner', 'blue'), ('None', 'none')], max_length=25)),
                ('method_of_victory', models.CharField(blank=True, choices=[('Knockout', 'ko'), ('Technical Knockout', 'tko'), ('Submission', 'sub'), ('Decision', 'dec')], max_length=25)),
                ('draw', models.BooleanField(default=False)),
                ('weight_class', models.CharField(choices=[(105, 'atom'), (115, 'straw'), (125, 'fly'), (135, 'bantam'), (145, 'feather'), (155, 'light'), (170, 'welter'), (185, 'middle'), (205, 'light_heavy'), (265, 'heavy')], max_length=25)),
                ('title', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=25)),
                ('event', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('notable_win', models.BooleanField(default=True)),
                ('blue_corner', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_corner', to='kach_backend_endpoints.fighter')),
                ('red_corner', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_corner', to='kach_backend_endpoints.fighter')),
            ],
        ),
        migrations.AddField(
            model_name='fighter',
            name='notable_wins',
            field=models.ManyToManyField(blank=True, to='kach_backend_endpoints.Fight'),
        ),
    ]
