# Generated by Django 3.1.4 on 2021-01-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0015_auto_20210112_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='notable_wins',
        ),
        migrations.AddField(
            model_name='fighter',
            name='notable_wins',
            field=models.ManyToManyField(blank=True, null=True, related_name='_fighter_notable_wins_+', to='kach_backend_endpoints.Fighter'),
        ),
    ]
