# Generated by Django 3.1.4 on 2021-01-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0016_auto_20210113_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='round',
            field=models.CharField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'forth'), (5, 'fifth')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
