# Generated by Django 3.1.4 on 2021-01-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0016_auto_20210112_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='notable_wins',
            field=models.ManyToManyField(blank=True, related_name='_fighter_notable_wins_+', to='kach_backend_endpoints.Fighter'),
        ),
    ]
