# Generated by Django 3.1.4 on 2021-01-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0017_auto_20210112_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='notable_victories',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
