# Generated by Django 3.1.4 on 2021-01-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0017_fight_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='title',
        ),
        migrations.AddField(
            model_name='fight',
            name='title_fight',
            field=models.BooleanField(default=False),
        ),
    ]
