# Generated by Django 3.1.4 on 2021-01-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0018_auto_20210113_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='video',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
