# Generated by Django 3.1.4 on 2021-01-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0018_fighter_notable_victories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('winner', models.CharField(blank=True, choices=[('Red Corner', 'red'), ('Blue Corner', 'blue'), ('None', 'none')], max_length=25)),
                ('method_of_victory', models.CharField(blank=True, choices=[('Knockout', 'ko'), ('Technical Knockout', 'tko'), ('Submission', 'sub')], max_length=25)),
                ('draw', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='no', max_length=10)),
                ('video', models.CharField(max_length=25)),
                ('event', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('blue_corner', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_corner', to='kach_backend_endpoints.fighter')),
                ('red_corner', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_corner', to='kach_backend_endpoints.fighter')),
            ],
        ),
    ]
