# Generated by Django 3.1.4 on 2021-01-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0020_auto_20210113_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='description',
            field=models.TextField(default='fight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fight',
            name='blue_corner',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fight',
            name='red_corner',
            field=models.CharField(max_length=50),
        ),
    ]
