# Generated by Django 3.1.4 on 2021-02-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0021_auto_20210113_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_class', models.CharField(choices=[(105, 'atom'), (115, 'straw'), (125, 'fly'), (135, 'bantam'), (145, 'feather'), (155, 'light'), (170, 'welter'), (185, 'middle'), (205, 'light_heavy'), (265, 'heavy')], max_length=15)),
                ('Fighters', models.ManyToManyField(blank=True, to='kach_backend_endpoints.Fighter')),
            ],
        ),
    ]
