# Generated by Django 3.1.4 on 2021-02-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0022_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='Fighters',
        ),
        migrations.AddField(
            model_name='division',
            name='fighters',
            field=models.ManyToManyField(blank=True, to='kach_backend_endpoints.Fighter'),
        ),
        migrations.AddField(
            model_name='division',
            name='gender',
            field=models.CharField(choices=[('Men', 'men'), ('Women', 'women')], default='Men', max_length=15),
        ),
    ]
