# Generated by Django 3.1.4 on 2021-02-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0023_auto_20210204_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='pound_for_pound',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='division',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='Men', max_length=15),
        ),
        migrations.AlterField(
            model_name='division',
            name='weight_class',
            field=models.CharField(choices=[('Fly', 'Flyweight'), ('Bantam', 'Bantamweight'), ('Feather', 'Featherweight'), ('Light', 'Lightweight'), ('Welter', 'Welterweight'), ('Middle', 'Middleweight'), ('Light Heavy', 'Light Heavyweight'), ('Heavy', 'Heavyweight')], max_length=15),
        ),
    ]
