# Generated by Django 3.1.4 on 2021-02-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0024_auto_20210204_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='height',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='losses_via_decision',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='losses_via_knockout',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='losses_via_submission',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='no_contests',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='notable_wins',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='reach',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='style',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='weight_class',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='wins',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='wins_via_decision',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='wins_via_knockout',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='wins_via_submission',
        ),
    ]
