# Generated by Django 3.1.4 on 2021-02-04 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0025_auto_20210204_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='isChampion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fighter',
            name='rank',
            field=models.IntegerField(default=1, verbose_name=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
    ]
