# Generated by Django 3.1.4 on 2021-02-04 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0027_auto_20210204_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='rank',
            field=models.IntegerField(blank=True, verbose_name=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
