# Generated by Django 3.1.4 on 2021-02-05 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0027_auto_20210204_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fighter',
            name='fighter_image',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='height',
            field=models.CharField(default='5ft9', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='losses',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='reach',
            field=models.DecimalField(decimal_places=1, default=72, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='weight_class',
            field=models.CharField(default='Lightweight', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='wins',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='wins_via_dec',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='wins_via_ko',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='wins_via_sub',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fighter',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
