# Generated by Django 3.1.4 on 2021-02-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0028_auto_20210205_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='weight_class',
            field=models.CharField(max_length=100),
        ),
    ]
