# Generated by Django 3.1.4 on 2021-02-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0028_auto_20210204_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='weight_class',
            field=models.CharField(choices=[(105, 'atom'), (115, 'straw'), (125, 'fly'), (135, 'bantam'), (145, 'feather'), (155, 'light'), (170, 'welter'), (185, 'middle'), (205, 'light_heavy'), (265, 'heavy')], default='Flyweight', max_length=15),
            preserve_default=False,
        ),
    ]
