# Generated by Django 3.1.4 on 2021-02-05 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0030_auto_20210204_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='draws',
            field=models.IntegerField(default=0, verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='fighter',
            name='height',
            field=models.CharField(default='5ft', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='losses',
            field=models.IntegerField(default=1, verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='reach',
            field=models.DecimalField(decimal_places=1, default=72.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='wins',
            field=models.IntegerField(default=1, verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='wins_via_dec',
            field=models.IntegerField(default=1, verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='wins_via_ko',
            field=models.IntegerField(default=1, verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='wins_via_sub',
            field=models.IntegerField(default=1, verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
