# Generated by Django 3.1.4 on 2021-02-05 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0031_auto_20210205_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)]),
            preserve_default=False,
        ),
    ]
