# Generated by Django 3.1.4 on 2021-02-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0032_fighter_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='fighter_image',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
