# Generated by Django 3.1.4 on 2021-02-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0034_auto_20210205_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
