# Generated by Django 3.1.4 on 2021-02-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_backend_endpoints', '0035_auto_20210205_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='fighter_image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='weight_class',
            field=models.CharField(max_length=30),
        ),
    ]
