# Generated by Django 3.1.3 on 2020-11-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=500)),
                ('video_id', models.CharField(max_length=50)),
                ('video_description', models.TextField()),
                ('upload_date', models.DateTimeField()),
                ('video_thumbnail', models.CharField(max_length=300)),
                ('playlist_id', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubePlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=200)),
                ('playlist_id', models.TextField(max_length=35)),
                ('playlist_videos', models.ManyToManyField(blank=True, to='kach_api_endpoints.YoutubeVideo')),
            ],
        ),
    ]
