# Generated by Django 3.1.4 on 2020-12-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
