# Generated by Django 3.1.4 on 2021-01-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0002_delete_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_link', models.CharField(max_length=15)),
                ('caption', models.TextField()),
                ('media', models.CharField(max_length=350)),
                ('type', models.CharField(choices=[('Image', 'GraphVideo'), ('Video', 'GraphImage')], max_length=25)),
                ('time_stamp', models.IntegerField()),
                ('thumbnail', models.CharField(max_length=350)),
                ('likes', models.IntegerField()),
                ('views', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('video_url', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
    ]
