# Generated by Django 3.1.1 on 2020-11-07 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0002_matchday_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchday',
            name='points_total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
