# Generated by Django 3.1.1 on 2020-11-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0002_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song',
            new_name='song_title',
        ),
    ]
