# Generated by Django 3.1.1 on 2020-11-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0003_auto_20201107_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchday',
            old_name='game_week',
            new_name='gameweek',
        ),
    ]
