# Generated by Django 3.1.4 on 2021-01-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
    ]
