# Generated by Django 3.1.4 on 2021-01-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0004_remove_post_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Image', 'GraphVideo'), ('Video', 'GraphImage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
