# Generated by Django 3.1.1 on 2020-11-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0005_content_imdblist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='release_date',
            field=models.IntegerField(default=2020),
        ),
    ]
