# Generated by Django 3.1.1 on 2020-11-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0006_auto_20201107_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdblist',
            name='media_type',
            field=models.CharField(default='movie', max_length=20),
        ),
    ]
