# Generated by Django 3.1.4 on 2021-01-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0006_remove_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.BigIntegerField(),
        ),
    ]
