# Generated by Django 3.1.4 on 2021-01-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0007_auto_20210119_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
