# Generated by Django 3.1.1 on 2020-12-07 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0008_player_current_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_total',
            new_name='points_total',
        ),
        migrations.AddField(
            model_name='player',
            name='current_gameweek',
            field=models.IntegerField(default=11, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(38)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='transfers_total',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(570)]),
            preserve_default=False,
        ),
    ]
