# Generated by Django 3.1.4 on 2021-01-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0008_auto_20210119_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.TextField(),
        ),
    ]
