# Generated by Django 3.1.4 on 2021-01-29 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0009_auto_20210119_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_name', models.CharField(max_length=150)),
                ('chip_date', models.DateTimeField()),
                ('chip_matchday', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(38)])),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='chips',
            field=models.ManyToManyField(blank=True, to='kach_api_endpoints.Chips'),
        ),
    ]
