# Generated by Django 3.1.4 on 2020-12-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0009_auto_20201207_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='release_date',
            field=models.IntegerField(),
        ),
    ]
