# Generated by Django 3.1.4 on 2021-05-24 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0010_auto_20210205_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points_on_transfers',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
    ]
