# Generated by Django 3.1.4 on 2020-12-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0010_auto_20201214_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='release_date',
            new_name='released',
        ),
    ]
