# Generated by Django 3.1.4 on 2020-12-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0011_auto_20201214_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imdblist',
            name='content',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='ImdbList',
        ),
    ]
