# Generated by Django 3.1.4 on 2021-01-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0011_auto_20210129_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='chip_date',
            field=models.DateField(),
        ),
    ]
