# Generated by Django 3.1.4 on 2021-05-24 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0012_player_team_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_gameweek_points',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.CharField(default='team name', max_length=1000),
            preserve_default=False,
        ),
    ]
