# Generated by Django 3.1.4 on 2021-01-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kach_api_endpoints', '0013_chip_chip_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='chip',
            new_name='chips',
        ),
        migrations.AlterField(
            model_name='chip',
            name='chip_date',
            field=models.DateTimeField(),
        ),
    ]
